export enum PaymentStatus {
  Created = 'created',
  Approved = 'approved',
  Rejected = 'rejected',
  Pending = 'pending',
  InProcess = 'in_process',
  Processing = 'processing',
  ActionRequired = 'action_required',
  InMediation = 'in_mediation',
  Error = 'error',
  Failed = 'failed',
  Processed = 'processed',
  Expired = 'expired',
  Cancelled = 'cancelled',
  Canceled = 'canceled',
  Refunded = 'refunded',
  PartiallyRefunded = 'partially_refunded',
  ChargedBack = 'charged_back',
}
