import { DashboardResponse } from '../models/dashboard-response.model';

export const EMPTY_DASHBOARD_RESPONSE: DashboardResponse = {
  generatedAtUtc: '',
  period: {
    fromUtc: '',
    toUtc: '',
    days: 0,
  },
  overview: {
    totalRaised: 0,
    totalGoal: 0,
    fundingPercent: 0,
    totalGifts: 0,
    fullyFundedGifts: 0,
    paidContributions: 0,
    uniqueContributors: 0,
    approvedPayments: 0,
    failedPayments: 0,
  },
  gifts: {
    total: 0,
    available: 0,
    unavailable: 0,
    fullyFunded: 0,
    partiallyFunded: 0,
    withoutContributions: 0,
    goalAmount: 0,
    raisedAmount: 0,
    remainingAmount: 0,
    averageFundingPercent: 0,
  },
  contributions: {
    total: 0,
    paid: 0,
    pending: 0,
    cancelled: 0,
    paidAmount: 0,
    pendingAmount: 0,
    cancelledAmount: 0,
    averagePaidAmount: 0,
    uniqueContributors: 0,
    messagesCount: 0,
    periodPaidCount: 0,
    periodPaidAmount: 0,
  },
  payments: {
    total: 0,
    approved: 0,
    pending: 0,
    failed: 0,
    other: 0,
    pix: 0,
    card: 0,
    approvedWithoutContribution: 0,
    approvedAmount: 0,
    pendingAmount: 0,
    failedAmount: 0,
    successRate: 0,
    failureRate: 0,
  },
  messages: {
    total: 0,
    contributionMessages: 0,
    paymentIntentMessages: 0,
    latestMessageAtUtc: '',
  },
  requests: {
    total: 0,
    successful: 0,
    clientErrors: 0,
    serverErrors: 0,
    authenticated: 0,
    anonymous: 0,
    slowRequests: 0,
    successRate: 0,
    clientErrorRate: 0,
    serverErrorRate: 0,
    averageDurationMilliseconds: 0,
    maxDurationMilliseconds: 0,
    lastRequestAtUtc: '',
  },
  monitoring: {
    databaseStatus: '',
    applicationLogsStatus: '',
    metricsStatus: '',
    pendingPayments: 0,
    pendingPixPayments: 0,
    failedPayments: 0,
    approvedPaymentsWithoutContribution: 0,
    serverErrorRequests: 0,
    slowRequests: 0,
    averageRequestDurationMilliseconds: 0,
    lastPaymentAtUtc: '',
    lastContributionAtUtc: '',
    lastRequestAtUtc: '',
    notes: [],
  },
  contributionsByDay: [],
  paymentsByStatus: [],
  paymentsByMethod: [],
  giftsByCategory: [],
  requestsByStatus: [],
  requestsByPath: [],
  topGiftsByRaised: [],
  recentMessages: [],
  recentRequests: [],
  recentPayments: [],
  recentFailedPayments: [],
  recentContributions: [],
};
