export const PAYMENT_ERROR_CODES = {
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  INSUFFICIENT_AMOUNT: 'INSUFFICIENT_AMOUNT',
  DUPLICATE_ORDER: 'DUPLICATE_ORDER',
  PIX_EXPIRED: 'PIX_EXPIRED',
  PIX_REJECTED: 'PIX_REJECTED',
  INVALID_CARD_TOKEN: 'INVALID_CARD_TOKEN',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type PaymentErrorCode = typeof PAYMENT_ERROR_CODES[keyof typeof PAYMENT_ERROR_CODES];
